import { loadingHtml } from './markup';
import type { Close, LoadingOptions } from './types';

type Notice = { kind: 'loading' | 'toast'; message: string; mask?: boolean };
const FADE_TIME = 140;
const RESIZE_TIME = 180;

let current: Notice | undefined;
let layer: HTMLDivElement | undefined;
let element: HTMLDivElement | undefined;
let content: HTMLDivElement | undefined;
let dots: HTMLDivElement | undefined;
let label: HTMLSpanElement | undefined;
let removeTimer: ReturnType<typeof setTimeout> | undefined;
let toastTimer: ReturnType<typeof setTimeout> | undefined;
let resizeTimer: ReturnType<typeof setTimeout> | undefined;
const pending: Notice[] = [];

function cancelTimers() {
  clearTimeout(removeTimer);
  clearTimeout(toastTimer);
}

function blockBackground(event: Event) {
  if (layer && !layer.contains(event.target as Node)) {
    event.preventDefault();
    event.stopImmediatePropagation();
  }
}

function setMask(mask: boolean) {
  layer?.classList.toggle('pkg-ui-mask', mask);
  // Also catch clicks/submissions generated by a focused background control.
  document.removeEventListener('click', blockBackground, true);
  document.removeEventListener('submit', blockBackground, true);
  if (mask) {
    document.addEventListener('click', blockBackground, true);
    document.addEventListener('submit', blockBackground, true);
  }
}

function ensureElement() {
  if (element) return;
  layer =
    document.querySelector<HTMLDivElement>('[data-initial-loading]') ??
    undefined;
  if (!layer) {
    const container = document.createElement('div');
    container.innerHTML = loadingHtml;
    layer = container.firstElementChild as HTMLDivElement;
    document.body.appendChild(layer);
  }
  layer.removeAttribute('data-initial-loading');
  element = layer.querySelector<HTMLDivElement>('.pkg-ui-notice')!;
  content = element.querySelector<HTMLDivElement>('.pkg-ui-content')!;
  dots = element.querySelector<HTMLDivElement>('.pkg-ui-dots')!;
  label = element.querySelector<HTMLSpanElement>('.pkg-ui-label')!;
}

function render() {
  if (!current) return;
  const previous = element?.getBoundingClientRect();
  clearTimeout(resizeTimer);
  ensureElement();
  const card = element!;
  card.style.transitionProperty = 'opacity';
  resetSize();
  card.classList.remove('pkg-ui-loading', 'pkg-ui-toast');
  card.classList.add(`pkg-ui-${current.kind}`);
  dots!.hidden = current.kind !== 'loading';
  label!.hidden = !current.message;
  label!.textContent = current.message;
  if (current.kind === 'loading' && !current.message) {
    card.setAttribute('aria-label', '正在加载页面');
  } else {
    card.removeAttribute('aria-label');
  }
  setMask(current.kind === 'loading' && pending.some((entry) => entry.mask));
  const next = card.getBoundingClientRect();
  if (
    previous &&
    (previous.width !== next.width || previous.height !== next.height)
  ) {
    content!.style.width = `${content!.getBoundingClientRect().width}px`;
    content!.style.maxWidth = 'none';
    card.style.width = `${previous.width}px`;
    card.style.height = `${previous.height}px`;
    void card.offsetWidth;
    card.style.transitionProperty = '';
    card.style.width = `${next.width}px`;
    card.style.height = `${next.height}px`;
    resizeTimer = setTimeout(resetSize, RESIZE_TIME + 40);
  } else {
    void card.offsetWidth;
    card.style.transitionProperty = '';
  }
  card.classList.add('pkg-ui-visible');
}

function resetSize() {
  if (!element || !content) return;
  element.style.width = '';
  element.style.height = '';
  content.style.width = '';
  content.style.maxWidth = '';
}

function remove() {
  clearTimeout(resizeTimer);
  setMask(false);
  if (layer?.parentNode) layer.parentNode.removeChild(layer);
  layer = undefined;
  element = undefined;
  content = undefined;
  dots = undefined;
  label = undefined;
}

function dismiss(kind: Notice['kind']) {
  current = undefined;
  cancelTimers();
  setMask(false);
  if (!element) return;
  if (kind === 'loading') {
    // Hold the current geometry if a message/size transition is still in flight.
    const size = element.getBoundingClientRect();
    clearTimeout(resizeTimer);
    element.style.transitionProperty = 'opacity';
    element.style.width = `${size.width}px`;
    element.style.height = `${size.height}px`;
  }
  // Release interaction immediately; only the visual layer finishes fading out.
  element.classList.remove('pkg-ui-visible');
  removeTimer = setTimeout(remove, FADE_TIME);
}

function assertBody() {
  if (typeof document === 'undefined' || !document.body) {
    throw new Error(
      '@packages/ui must be called after document.body is ready.',
    );
  }
}

export function showLoading(options: LoadingOptions): Close {
  assertBody();
  cancelTimers();
  if (current?.kind !== 'loading') pending.length = 0;
  const entry: Notice = {
    kind: 'loading',
    message: options.message ?? '',
    mask: options.mask ?? false,
  };
  pending.push(entry);
  current = entry;
  render();
  return () => {
    const index = pending.indexOf(entry);
    if (index === -1) return;
    pending.splice(index, 1);
    current = pending[pending.length - 1];
    if (!current) dismiss('loading');
    else render();
  };
}

export function showToast(message: string, duration: number): Close {
  assertBody();
  cancelTimers();
  pending.length = 0;
  const entry: Notice = { kind: 'toast', message };
  current = entry;
  render();
  const close = () => {
    if (current === entry) dismiss('toast');
  };
  if (duration > 0) toastTimer = setTimeout(close, duration);
  return close;
}
